import { arraySidebar } from "vuepress-theme-hope";

export const tech = arraySidebar([
  {
    text: "OpenAI",
    icon: "info",
    link: "OpenAI/",
    prefix: "OpenAI/",
    collapsible: true,
    children: "structure",
  },
  {
    text: "Azure",
    icon: "info",
    link: "Azure/",
    prefix: "Azure/",
    collapsible: true,
    children: "structure",
  },
  {
    text: "Card",
    icon: "file",
    link: "Card/",
    prefix: "Card/",
    collapsible: true,
    children: "structure",
  },
  {
    text: "Cloudflare",
    icon: "program",
    link: "Cloudflare/",
    prefix: "Cloudflare/",
    collapsible: true,
    children: "structure",
  },
  {
    text: "Vercel",
    icon: "info",
    link: "Vercel/",
    prefix: "Vercel/",
    collapsible: true,
    children: "structure",
  },
  {
    text: "GFW",
    icon: "program",
    link: "GFW/",
    prefix: "GFW/",
    collapsible: true,
    children: "structure",
  },
  {
    text: "Network",
    icon: "program",
    link: "Network/",
    prefix: "Network/",
    collapsible: true,
    children: "structure",
  },
  {
    text: "Shell",
    icon: "program",
    link: "Shell/",
    prefix: "Shell/",
    collapsible: true,
    children: "structure",
  },
  {
    text: "SelfHosted",
    icon: "program",
    link: "SelfHosted/",
    prefix: "SelfHosted/",
    collapsible: true,
    children: "structure",
  },
  {
    text: "Other",
    icon: "program",
    link: "Other/",
    prefix: "Other/",
    collapsible: true,
    children: "structure",
  },
]);